"use strict"

module.exports = {
  url: "https://banyh.github.io/",
  title: "讀書筆記",
  tagline: "Python愛好者、ML Engineer",
  copyright: "© 2019 banyh, All rights reserved",
  author: {
    name: "Bany Hong",
    bio: "Python愛好者、ML Engineer",
    contacts: {
      linkedin: "",
      github: "https://github.com/banyh",
      stackoverflow: "https://askubuntu.com/users/792091/ping-chu-hung",
      freecodecamp: "",
      twitter: "",
    },
  },
  labels: [
    {
      tag: "python",
      tech: "Python",
      name: "DiPython",
      size: 20,
      color: "deepskyblue",
    },
    {
      tag: "ffmpeg",
      tech: "ffmpeg",
      name: "FaFilm",
      size: 20,
      color: "lightgreen",
    },
    {
      tag: "git",
      tech: "Git",
      name: "FaGithub",
      size: 20,
      color: "goldenrod",
    },
    {
      tag: "machinelearning",
      tech: "Machine Learning",
      name: "FaDiceD6",
      size: 20,
      color: "violet",
    },
    {
      tag: "ubuntu",
      tech: "Ubuntu",
      name: "FaUbuntu",
      size: 20,
      color: "green",
    },
    {
      tag: "hardware",
      tech: "Hardware",
      name: "FaDesktop",
      size: 20,
      color: "darkgoldenrod",
    },
    {
      tag: "deeplearning",
      tech: "Deep Learning",
      name: "FaDiceD20",
      size: 20,
      color: "darkorange",
    },
    {
      tag: "nlp",
      tech: "Natural Language Processing",
      name: "MdTranslate",
      size: 20,
      color: "darkcyan",
    },
    {
      tag: "cv",
      tech: "Computer Vision",
      name: "IoIosEye",
      size: 20,
      color: "darkkhaki",
    },
    {
      tag: "audio",
      tech: "Audio",
      name: "FaSoundcloud",
      size: 20,
      color: "darkolivegreen",
    },
    {
      tag: "others",
      tech: "Others",
      name: "FaRegLaughBeam",
      size: 20,
      color: "darkorchid",
    },
  ],
}
